/*
 * Copyright (c) 2022 Space Cubics, LLC.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef SCOBCA1_FPGA_TEST_HRMEM_TEST_H_
#define SCOBCA1_FPGA_TEST_HRMEM_TEST_H_

#include <zephyr/kernel.h>

/* Base address */
#define SCOBCA1_FPGA_HRMEM_MIRROR_BASE_ADDR  (0x60000000)
#define SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR    (0x40500000)

/* Offset */
#define HRMEM_ECCCOLENR_OFFSET     (0x0000) /* ECC Error Collect Enable Register */
#define HRMEM_MEMSCRCTRLR_OFFSET   (0x0008) /* Memory Scrubing Control Register */
#define HRMEM_INTSTR_OFFSET        (0x0010) /* HRMEM Interrupt Status Register */
#define HRMEM_INTENR_OFFSET        (0x0014) /* HRMEM Interrupt Enable Register */
#define HRMEM_ECC1ERRCNTR_OFFSET   (0x0020) /* 1Bit ECC Error Count Register */
#define HRMEM_ECDISCNTR_OFFSET     (0x0028) /* ECC Correct Data Discard Count Register */
#define HRMEM_ERRCNTCLRR_OFFSET    (0x002C) /* Error Count Clear Register */
#define HRMEM_ECCERRADMR_OFFSET    (0x0030) /* ECC Error Address Monitor Register */
#define HRMEM_PFEMDCTLR_OFFSET     (0x0070) /* Prefetch Mode Control Register */
#define HRMEM_SPEPFENR_OFFSET      (0x0074) /* Special Prefetch Enable Register */
#define HRMEM_SPEPFADRSETR1_OFFSET (0x0080) /* Special Prefetch Address Setting Register 1 */
#define HRMEM_SPEPFADRSETR2_OFFSET (0x0084) /* Special Prefetch Address Setting Register 2 */
#define HRMEM_VER_OFFSET           (0xF000) /* HRMEM IP Version Register */

/* HRMEM Control Register */
#define SCOBCA1_FPGA_HRMEM_ECCCOLENR (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_ECCCOLENR_OFFSET)
#define SCOBCA1_FPGA_HRMEM_MEMSCRCTRLR (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_MEMSCRCTRLR_OFFSET)
#define SCOBCA1_FPGA_HRMEM_INTSTR (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_INTSTR_OFFSET)
#define SCOBCA1_FPGA_HRMEM_INTENR (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_INTENR_OFFSET)
#define SCOBCA1_FPGA_HRMEM_ECC1ERRCNTR (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_ECC1ERRCNTR_OFFSET)
#define SCOBCA1_FPGA_HRMEM_ECDISCNTR (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_ECDISCNTR_OFFSET)
#define SCOBCA1_FPGA_HRMEM_ERRCNTCLRR (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_ERRCNTCLRR_OFFSET)
#define SCOBCA1_FPGA_HRMEM_ECCERRADMR (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_ECCERRADMR_OFFSET)
#define SCOBCA1_FPGA_HRMEM_PFEMDCTLR (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_PFEMDCTLR_OFFSET)
#define SCOBCA1_FPGA_HRMEM_SPEPFENR (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_SPEPFENR_OFFSET)
#define SCOBCA1_FPGA_HRMEM_SPEPFADRSETR1 (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_SPEPFADRSETR1_OFFSET)
#define SCOBCA1_FPGA_HRMEM_SPEPFADRSETR2 (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_SPEPFADRSETR2_OFFSET)
#define SCOBCA1_FPGA_HRMEM_VER (SCOBCA1_FPGA_HRMEM_CTRL_BASE_ADDR + HRMEM_VER_OFFSET)

uint32_t hrmem_rw(uint32_t size, uint32_t start_val, uint32_t *next_val);
uint32_t hrmem_test(uint32_t test_no);

#endif /* SCOBCA1_FPGA_TEST_HRMEM_TESET_H_ */
