/*
 * Copyright (c) 2022 Space Cubics, LLC.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef SCOBCA1_FPGA_TEST_I2C_TEST_H_
#define SCOBCA1_FPGA_TEST_I2C_TEST_H_

#include <zephyr/kernel.h>

/* Base address */
#define SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR  (0x4F020000)
#define SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR  (0x4F030000)

/* Offset */
#define I2CM_ENR_OFFSET     (0x0000) /* I2C Master Enable Register */
#define I2CM_TXFIFOR_OFFSET (0x0004) /* I2C Master TX FIFO Register */
#define I2CM_RXFIFOR_OFFSET (0x0008) /* I2C Master RX FIFO Register */
#define I2CM_BSR_OFFSET     (0x000C) /* I2C Master Bus Status Register */
#define I2CM_ISR_OFFSET     (0x0010) /* I2C Master Interrupt Status Register */
#define I2CM_IER_OFFSET     (0x0014) /* I2C Master Interrupt Enable Register */
#define I2CM_FIFOSR_OFFSET  (0x0018) /* I2C Master FIFO Status Register */
#define I2CM_FIFORR_OFFSET  (0x001C) /* I2C Master FIFO Reset Register */
#define I2CM_FTLSR_OFFSET   (0x0020) /* I2C Master FIFO Threshold Level Setting Register */
#define I2CM_SCLTSR_OFFSET  (0x0024) /* I2C Master SCL Timeout Setting Register */
#define I2CM_THDSTAR_OFFSET (0x0030) /* I2C Master START Hold Timing Setting Register */
#define I2CM_TSUSTOR_OFFSET (0x0034) /* I2C Master STOP Setup Timing Setting Register */
#define I2CM_TSUSTAR_OFFSET (0x0038) /* I2C Master Repeated START Setup Timing Setting Register */
#define I2CM_THIGHR_OFFSET  (0x003C) /* I2C Master Clock High Timing Setting Register */
#define I2CM_THDDATR_OFFSET (0x0040) /* I2C Master Data Hold Timing Setting Register */
#define I2CM_TSUDATR_OFFSET (0x0044) /* I2C Master Data Setup Timing Setting Register */
#define I2CM_TBUFR_OFFSET   (0x0048) /* I2C Master Bus Free Timing Setting Register */
#define I2CM_TBSMPLR_OFFSET (0x004C) /* I2C Master Bus Sampling Timing Setting Register */
#define I2CM_VER_OFFSET     (0xF000) /* I2C Master Controller IP Version Register */

/* Internal I2C Register */
#define SCOBCA1_FPGA_INTERNAL_I2CM_ENR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR +  I2CM_ENR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_TXFIFOR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_TXFIFOR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_RXFIFOR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR +  I2CM_RXFIFOR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_BSR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_BSR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_ISR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_ISR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_IER (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_IER_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_FIFOSR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_FIFOSR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_FIFORR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_FIFORR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_FTLSR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_FTLSR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_2CM_SCLTSR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_SCLTSR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_THDSTAR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_THDSTAR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_2CM_TSUSTOR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_TSUSTOR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_TSUSTAR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_TSUSTAR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_THIGHR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_THIGHR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_THDDATR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_THDDATR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_TSUDATR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_TSUDATR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_TBUFR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_TBUFR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_TBSMPLR (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + I2CM_TBSMPLR_OFFSET)
#define SCOBCA1_FPGA_INTERNAL_I2CM_VER (SCOBCA1_FPGA_INTERNAL_I2C_BASE_ADDR + + I2CM_VER_OFFSET)

/* Extenal I2C Register */
#define SCOBCA1_FPGA_EXTERNAL_I2CM_ENR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR +  I2CM_ENR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_TXFIFOR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_TXFIFOR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_RXFIFOR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR +  I2CM_RXFIFOR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_BSR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_BSR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_ISR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_ISR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_IER (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_IER_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_FIFOSR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_FIFOSR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_FIFORR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_FIFORR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_FTLSR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_FTLSR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_2CM_SCLTSR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_SCLTSR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_THDSTAR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_THDSTAR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_2CM_TSUSTOR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_TSUSTOR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_TSUSTAR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_TSUSTAR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_THIGHR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_THIGHR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_THDDATR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_THDDATR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_TSUDATR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_TSUDATR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_TBUFR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_TBUFR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_TBSMPLR (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + I2CM_TBSMPLR_OFFSET)
#define SCOBCA1_FPGA_EXTERNAL_I2CM_VER (SCOBCA1_FPGA_EXTERNAL_I2C_BASE_ADDR + + I2CM_VER_OFFSET)

uint32_t internal_i2c_test(void);

#endif /* SCOBCA1_FPGA_TEST_I2C_TESET_H_ */
